apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-flagger
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./gitops/argo-apps/flagger
    repoURL: git@github.com:asoni90/linkerd-demo.git
